### ISSUE TITLE
Ideas overview

### ISSUE THREAD

**Issue by michie1** [michie1/bc#13]
- [x] Allow space between `BC180` in first row of a new post & ignore caps #18
- [ ] Show message in spreadsheet an item was not being added, with a specific error. (Item not found)
- [x] Ignore spaces in item type & ignore caps #19
- [x] Ignore ' " ″ in item type #42
- [ ] Write readme how to install on Windows.
- [x] ~~Create separate order for price alerts #3~~
- [x] Manual trigger via https #43
- [x] Deprecate directory config.dir #21
- [x] Add typesl #25 #26 https://docs.python.org/3/library/typing.html
- [x] Add formatter #27
- [ ] Use .env instead of config.py
- [ ] Store state in pickle/sqlite instead of json?
- [x] Testing #1 
- [x] Test coverage #37
- [x] Run test in each PR with Github Actions #33
- [ ] Calculate the amount of rows needed for the spreadsheet instead of using a fixed value of 200.

**Comment by bcvanmeurs** [comment]
> - [ ] Deprecate directory config.dir

By accident I found this commit: 442445fb29547caac9eb8f64378769390ab132b5. So the config.directory was added to make the script work with cronjob. I am not familiar with cronjob and don't know if this is necessary but I think it is useful to know why you @michie1  put it there in the first place.
